Evaluate accessibility
AbuTalha3/Portfolio-Setup pull request #10
Opened 2023-06-13 13:14 UTC by AbuTalha3

In this branch, I have:-
- Added a page title.
- Added image text alternatives.
- Text headings - no issue found.
- color contrast - no issue found
- Resize- no issue found
- Interaction- The text is readable by a computer for the visually impaired person.
- Moving content- Animations already added.
- The basic structure of the page. It is already corresponding to the given Figma design.

2023-06-13 14:01 UTC, christianbiring1 requested changes
Hi @AbuTalha3 @anshuman7negi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 

## Highlights
- [ ] Great work on using the correct `heading` element, the interaction is good, keyboard access
- [ ] Descriptive PR `title` and `summary` :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] In the result section of the report you should include a statement pertaining to every point checked:
* If issues were found, you should link to the corresponding line of code in the Pull Request changes

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 14:01 UTC, christianbiring1 commented on index.html
> +    <title>Portfolio</title>
- [x] Great work on working on the page title, however, make sure it adequately and briefly describes the content of the page for better accessibility on the internet by Search Engines.

```suggestion
    <title>Abu's Portfolio</title>
```

2023-06-13 14:01 UTC, christianbiring1 commented on index.html
> +    <title>Portfolio</title>
- [ ] Or even `Abu FullStack Developer`

2023-06-13 14:01 UTC, christianbiring1 commented on index.html
>                      </ul>
- [x] KIndly make sure your `alternative text` have some descriptive text. The question you need to ask yourself is that in case the image is not displayed for some reason, will the user still have the idea of what that specific image is about?
Hint: Instead of `LinkedIn` you may consider saying `LinkedIn logo` and so on for all the logo

2023-06-13 14:01 UTC, christianbiring1 commented on index.html
>                              <li class="BSimage">FACEBOOK</li>
- [ ] Kindly make sure your page has a good contrast ratio as is the standard. You may consider checking readjusting your colors and make all the failing ratio to pass.
as you may see [here](https://www.aditus.io/button-contrast-checker/abutalha3-github-io-2023-06-13-at-13-41-20-677?failing) the results of your page
Hint: You can use [this](https://www.aditus.io/button-contrast-checker/) tool to check that.

2023-06-14 08:21 UTC, V-Blaze approved these changes
Hi @AbuTalha3, @anshuman7negi  

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Descriptive accessibility report :heavy_check_mark:
- Report checks are okay :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 08:45 UTC, merged